# Generated by Django 4.1 on 2023-09-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Rectificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rectificacion', models.CharField(max_length=12)),
                ('fecha', models.DateField()),
                ('interno', models.PositiveSmallIntegerField()),
                ('numero_acta', models.CharField(max_length=12)),
                ('rectificacion_pdf', models.FileField(upload_to='rectificaciones/')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresas')),
            ],
            options={
                'verbose_name_plural': 'Rectificaciones',
            },
        ),
        migrations.CreateModel(
            name='Internos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interno', models.PositiveSmallIntegerField()),
                ('chapa_mop', models.CharField(max_length=8)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresas')),
            ],
            options={
                'verbose_name_plural': 'Internos',
            },
        ),
        migrations.CreateModel(
            name='Actas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_acta', models.CharField(max_length=12)),
                ('fecha', models.DateField()),
                ('interno', models.PositiveSmallIntegerField()),
                ('descripcion', models.CharField(max_length=300)),
                ('intimacion', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('horas_intimacion', models.PositiveSmallIntegerField(choices=[(24, '24 horas'), (48, '48 horas'), (72, '72 horas')])),
                ('acta_pdf', models.FileField(upload_to='actas/')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresas')),
            ],
            options={
                'verbose_name_plural': 'Actas',
            },
        ),
    ]
