# Generated by Django 4.1 on 2023-11-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desinfeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interno', models.PositiveSmallIntegerField()),
                ('chapa_mop', models.CharField(max_length=8)),
                ('fecha_realizacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('desinfeccion_pdf', models.FileField(blank=True, null=True, upload_to='desinfecciones_pdfs/')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresas')),
            ],
        ),
    ]
